<script setup lang="ts">
import { computed } from "vue";
import type { AnalysisReport } from "../api/client";

/** `only` narrows the panel to the hypotheses that cite one finding (evidence detail view). */
const props = defineProps<{ report: AnalysisReport; findingLink: (id: string) => string; only?: string }>();

const explanationResult = computed(() => props.report.explanation);
const findingTitles = computed(() => new Map(props.report.findings.map((f) => [f.finding_id, f.title])));
const hypotheses = computed(() =>
  (explanationResult.value.explanation?.hypotheses ?? []).filter((h) => !props.only || h.finding_ids.includes(props.only)),
);
</script>

<template>
  <aside class="ai" :class="{ card: !only }" aria-labelledby="ai-title">
    <div class="head">
      <h2 id="ai-title">{{ only ? "AI hypotheses" : "Check first" }}</h2>
      <span class="muted small">AI suggestion · hypotheses unverified</span>
    </div>
    <template v-if="explanationResult.status === 'succeeded' && explanationResult.explanation">
      <ol v-if="!only" class="steps">
        <li v-for="(s, i) in explanationResult.explanation.investigation_steps" :key="i">{{ s.text }}</li>
      </ol>
      <div v-for="(h, i) in hypotheses" :key="i" class="hyp">
        <p><strong>Hypothesis — unverified</strong> <span class="muted">({{ h.likelihood }})</span>: {{ h.text }}</p>
        <p class="refs">
          Based on:
          <RouterLink v-for="id in h.finding_ids" :key="id" :to="findingLink(id)" class="ref">{{ findingTitles.get(id) ?? id }}</RouterLink>
        </p>
      </div>
      <p v-if="only && hypotheses.length === 0" class="muted">No hypotheses reference this finding.</p>
      <template v-if="!only">
        <p class="muted small">{{ explanationResult.explanation.summary }} Uncertainty: {{ explanationResult.explanation.uncertainty }}</p>
        <p class="muted small">Generated by {{ explanationResult.explanation.provider }}/{{ explanationResult.explanation.model }}. Numerical findings are authoritative.</p>
      </template>
    </template>
    <p v-else-if="explanationResult.status === 'disabled' || explanationResult.status === 'not_configured'">
      AI explanations are off. The numerical report is complete.
      <span v-if="explanationResult.status === 'not_configured' && explanationResult.reason" class="muted">({{ explanationResult.reason }})</span>
    </p>
    <p v-else-if="explanationResult.status === 'failed'" role="status">
      The explanation could not be generated ({{ explanationResult.reason ?? "unknown error" }}). Findings and evidence are unaffected.
    </p>
    <p v-else-if="explanationResult.status === 'skipped_no_findings'" class="muted">No findings to explain.</p>
    <p v-if="explanationResult.validation_notes?.length && !only" class="muted small">
      {{ explanationResult.validation_notes?.length }} AI item(s) were dropped or limited during validation.
    </p>
  </aside>
</template>

<style scoped>
.ai { display: flex; flex-direction: column; gap: 10px; }
.ai p { margin: 0; }
.head { display: flex; justify-content: space-between; align-items: baseline; gap: 12px; flex-wrap: wrap; }
.head h2 { margin: 0; }
.steps { margin: 0; padding-left: 22px; display: flex; flex-direction: column; gap: 8px; }
.hyp { padding-top: 8px; border-top: 1px solid var(--subtle); }
.ref { margin-right: var(--space); }
.refs { font-size: 0.85rem; }
.small { font-size: 0.8rem; }
</style>
