<script setup lang="ts">
import { computed, ref } from "vue";
import type { AnalysisReport } from "../api/client";

/** `only` narrows the panel to the hypotheses that cite one finding (evidence detail view). */
const props = defineProps<{ report: AnalysisReport; findingLink: (id: string) => string; only?: string }>();

const explanationResult = computed(() => props.report.explanation);
const findingTitles = computed(() => new Map(props.report.findings.map((f) => [f.finding_id, f.title])));
const open = ref(true);
const hypotheses = computed(() =>
  (explanationResult.value.explanation?.hypotheses ?? []).filter((h) => !props.only || h.finding_ids.includes(props.only)),
);
</script>

<template>
  <section :class="only ? 'inline' : 'panel'" :aria-labelledby="only ? undefined : 'ai-title'" :aria-label="only ? 'AI hypotheses' : undefined">
    <div v-if="!only" class="ph">
      <h2 id="ai-title">
        <button type="button" class="toggle" :aria-expanded="open" aria-controls="ai-body" @click="open = !open">
          <svg width="12" height="12" viewBox="0 0 12 12" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="M2.5 4.5 6 8l3.5-3.5" /></svg>
          Check first
        </button>
      </h2>
      <span class="sub">· AI suggestion, hypotheses unverified</span>
    </div>
    <div v-show="only || open" id="ai-body" :class="{ pb: !only }">
      <div v-if="only" class="lbl strong">AI hypotheses · unverified</div>
      <template v-if="explanationResult.status === 'succeeded' && explanationResult.explanation">
        <ol v-if="!only" class="steps">
          <li v-for="(s, i) in explanationResult.explanation.investigation_steps" :key="i">{{ s.text }}</li>
        </ol>
        <div v-for="(h, i) in hypotheses" :key="i" class="hyp">
          <p><strong>Hypothesis — unverified</strong> <span class="muted">({{ h.likelihood }})</span>: {{ h.text }}</p>
          <p class="refs">
            Based on:
            <RouterLink v-for="id in h.finding_ids" :key="id" :to="findingLink(id)" class="ref">{{ findingTitles.get(id) ?? id }}</RouterLink>
          </p>
        </div>
        <p v-if="only && hypotheses.length === 0" class="muted">No hypotheses reference this finding.</p>
        <template v-if="!only">
          <p class="lbl">{{ explanationResult.explanation.summary }} Uncertainty: {{ explanationResult.explanation.uncertainty }}</p>
          <p class="lbl foot">
            Generated by {{ explanationResult.explanation.provider }}/{{ explanationResult.explanation.model }}.
            Numerical findings are authoritative; the numbers on this page don't depend on AI.
          </p>
        </template>
      </template>
      <p v-else-if="explanationResult.status === 'disabled' || explanationResult.status === 'not_configured'">
        AI explanations are off. The numerical report is complete.
        <span v-if="explanationResult.status === 'not_configured' && explanationResult.reason" class="muted">({{ explanationResult.reason }})</span>
      </p>
      <p v-else-if="explanationResult.status === 'failed'" role="status">
        The explanation could not be generated ({{ explanationResult.reason ?? "unknown error" }}). Findings and evidence are unaffected.
      </p>
      <p v-else-if="explanationResult.status === 'skipped_no_findings'" class="muted">No findings to explain.</p>
      <p v-if="explanationResult.validation_notes?.length && !only" class="lbl">
        {{ explanationResult.validation_notes?.length }} AI item(s) were dropped or limited during validation.
      </p>
    </div>
  </section>
</template>

<style scoped>
.inline { display: flex; flex-direction: column; gap: 6px; font-size: 13px; }
p { margin: 0; }
.strong { font-weight: 500; }
.steps { margin: 0; padding-left: 20px; display: flex; flex-direction: column; gap: 8px; font-size: 13px; }
.hyp { padding-top: 8px; border-top: 1px solid var(--grid); font-size: 13px; display: flex; flex-direction: column; gap: 4px; }
.ref { margin-right: var(--space); }
.refs { font-size: 12px; }
.foot { margin-top: auto; }
.toggle { display: inline-flex; align-items: center; gap: 6px; min-height: 28px; padding: 0 6px 0 2px; margin-left: -4px; border: none; background: none; font: inherit; color: inherit; }
.toggle:hover { background: var(--hover); }
.toggle svg { transition: transform 120ms; }
.toggle[aria-expanded="false"] svg { transform: rotate(-90deg); }
</style>
