<script setup lang="ts">
import { computed } from "vue";
import type { AnalysisReport } from "../api/client";

const props = defineProps<{ report: AnalysisReport; findingLink: (id: string) => string; only?: string }>();
const ex = computed(() => props.report.explanation);
const titles = computed(() => new Map(props.report.findings.map((f) => [f.finding_id, f.title])));
const hypotheses = computed(() =>
  (ex.value.explanation?.hypotheses ?? []).filter((h) => !props.only || h.finding_ids.includes(props.only)),
);
</script>

<template>
  <aside class="card ai" aria-labelledby="ai-title">
    <h2 id="ai-title">AI explanation</h2>
    <template v-if="ex.status === 'succeeded' && ex.explanation">
      <p v-if="!only">{{ ex.explanation.summary }}</p>
      <div v-for="(h, i) in hypotheses" :key="i" class="hyp">
        <p><strong>Hypothesis — unverified</strong> <span class="muted">({{ h.likelihood }})</span>: {{ h.text }}</p>
        <p class="refs">
          Based on:
          <RouterLink v-for="id in h.finding_ids" :key="id" :to="findingLink(id)" class="ref">{{ titles.get(id) ?? id }}</RouterLink>
        </p>
      </div>
      <p v-if="only && hypotheses.length === 0" class="muted">No hypotheses reference this finding.</p>
      <template v-if="!only">
        <h3>Investigation steps</h3>
        <ol>
          <li v-for="(s, i) in ex.explanation.investigation_steps" :key="i">{{ s.text }}</li>
        </ol>
        <p class="muted">Uncertainty: {{ ex.explanation.uncertainty }}</p>
        <p class="muted small">Generated by {{ ex.explanation.provider }}/{{ ex.explanation.model }}. Numerical findings are authoritative.</p>
      </template>
    </template>
    <p v-else-if="ex.status === 'disabled' || ex.status === 'not_configured'">
      AI explanations are off. The numerical report is complete.
      <span v-if="ex.status === 'not_configured' && ex.reason" class="muted">({{ ex.reason }})</span>
    </p>
    <p v-else-if="ex.status === 'failed'" role="status">
      The explanation could not be generated ({{ ex.reason ?? "unknown error" }}). Findings and evidence are unaffected.
    </p>
    <p v-else-if="ex.status === 'skipped_no_findings'" class="muted">No findings to explain.</p>
    <p v-if="ex.validation_notes?.length && !only" class="muted small">
      {{ ex.validation_notes?.length }} AI item(s) were dropped or limited during validation.
    </p>
  </aside>
</template>

<style scoped>
.ai h2 { margin-top: 0; }
.ref { margin-right: var(--space); }
.refs { font-size: 0.85rem; margin-top: -6px; }
.small { font-size: 0.8rem; }
</style>
