/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Analyses */
        get: operations["list_analyses_api_analyses_get"];
        put?: never;
        /** Submit Analysis */
        post: operations["submit_analysis_api_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis */
        get: operations["get_analysis_api_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        /** Cancel Analysis */
        delete: operations["cancel_analysis_api_analyses__analysis_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses/{analysis_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_api_analyses__analysis_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runtime Config */
        get: operations["runtime_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/test-connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Connection */
        post: operations["test_connection_api_projects_test_connection_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_projects__project_id__get"];
        /** Update Project */
        put: operations["update_project_api_projects__project_id__put"];
        post?: never;
        /**
         * Delete Project
         * @description Hard delete, including the project's analyses and reports.
         */
        delete: operations["delete_project_api_projects__project_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project Health
         * @description One connection test per configured source; empty when the project has none.
         */
        get: operations["get_project_health_api_projects__project_id__health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisJob */
        AnalysisJob: {
            /** Analysis Id */
            analysis_id: string;
            /** Config Hash */
            config_hash: string;
            /** Created At */
            created_at: string;
            /**
             * Daily Episodes
             * @description Anomaly episodes per trend day, oldest first; null for days without enough data. Present once a report is saved.
             */
            daily_episodes?: (number | null)[] | null;
            /** Detector Version */
            detector_version: string;
            /** End Time */
            end_time: string;
            error?: components["schemas"]["JobError"] | null;
            explanation_status: components["schemas"]["ExplanationStatus"];
            /**
             * Finding Counts
             * @description Present once a report is saved.
             */
            finding_counts?: {
                [key: string]: number;
            } | null;
            /** Finished At */
            finished_at?: string | null;
            /** Report Available */
            report_available: boolean;
            scope: components["schemas"]["Scope"];
            /** Stages */
            stages: components["schemas"]["StageProgress"][];
            /** Started At */
            started_at?: string | null;
            state: components["schemas"]["JobState"];
            /**
             * @description Submitted by a user or by the project schedule.
             * @default manual
             */
            trigger: components["schemas"]["JobTrigger"];
        };
        /** AnalysisList */
        AnalysisList: {
            /** Items */
            items: components["schemas"]["AnalysisJob"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** AnalysisReport */
        AnalysisReport: {
            /** Analysis Id */
            analysis_id: string;
            /** Capabilities */
            capabilities: components["schemas"]["MetricCapability"][];
            /** Config Hash */
            config_hash: string;
            /** Coverage */
            coverage: components["schemas"]["SignalCoverage"][];
            /** Detector Version */
            detector_version: string;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Exclusions */
            exclusions: components["schemas"]["Exclusion"][];
            explanation: components["schemas"]["ExplanationResult"];
            /** Findings */
            findings: components["schemas"]["Finding"][];
            /** Generated At */
            generated_at: string;
            /**
             * Schema Version
             * @default 2.1
             * @enum {string}
             */
            schema_version: "2.0" | "2.1";
            scope: components["schemas"]["Scope"];
            /** @description Deprecated: the first source; use sources. */
            source?: components["schemas"]["SourceInfo"] | null;
            /**
             * Sources
             * @description Every source analysed (2.1); empty in 2.0 reports.
             */
            sources?: components["schemas"]["SourceInfo"][];
            state: components["schemas"]["ReportState"];
            trend_summary?: components["schemas"]["TrendSummary"] | null;
            /** Trends */
            trends: components["schemas"]["DailyTrend"][];
            windows: components["schemas"]["AnalysisWindows"];
        };
        /**
         * AnalysisSubmission
         * @description Body of POST /api/analyses. end_time is floored to the step server-side.
         */
        AnalysisSubmission: {
            /** End Time */
            end_time?: string | null;
            /** Project Id */
            project_id: string;
        };
        /** AnalysisSubmitted */
        AnalysisSubmitted: {
            analysis: components["schemas"]["AnalysisJob"];
            /**
             * Duplicate Of Active
             * @default false
             */
            duplicate_of_active: boolean;
        };
        /** AnalysisWindows */
        AnalysisWindows: {
            /** End Time */
            end_time: string;
            latest_day: components["schemas"]["TimeRange"];
            /** Step Seconds */
            step_seconds: number;
            trend: components["schemas"]["TimeRange"];
        };
        /**
         * BaselineMode
         * @enum {string}
         */
        BaselineMode: "whole_baseline" | "time_of_day";
        /** BasicAuth */
        BasicAuth: {
            /** Password Set */
            password_set: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "basic";
            /** Username */
            username: string;
        };
        /** BasicAuthInput */
        BasicAuthInput: {
            /**
             * Password
             * @description Omit to keep the stored password (update only).
             */
            password?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "basic";
            /** Username */
            username: string;
        };
        /** BearerAuth */
        BearerAuth: {
            /** Token Set */
            token_set: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "bearer";
        };
        /** BearerAuthInput */
        BearerAuthInput: {
            /**
             * Token
             * @description Omit to keep the stored token (update only).
             */
            token?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "bearer";
        };
        /**
         * CapabilityStatus
         * @enum {string}
         */
        CapabilityStatus: "supported" | "partial" | "unsupported" | "unverified";
        /** CloudflareSource */
        CloudflareSource: {
            /** Api Url */
            api_url: string;
            /** Hostnames */
            hostnames: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "cloudflare";
            /** Token Set */
            token_set: boolean;
            /** Zone Id */
            zone_id: string;
        };
        /**
         * CloudflareSourceInput
         * @description One Cloudflare zone, optionally narrowed to some of its hostnames.
         */
        CloudflareSourceInput: {
            /**
             * Api Token
             * @description API token with Analytics:Read on the zone (and optionally Zone:Read, to show its domain). Omit to keep the stored one (update only); not needed for synthetic://.
             */
            api_token?: string | null;
            /**
             * Api Url
             * @description GraphQL endpoint; synthetic://<scenario> for demo data.
             * @default https://api.cloudflare.com/client/v4/graphql
             */
            api_url: string;
            /**
             * Hostnames
             * @description Analyse only these hostnames; empty analyses the whole zone.
             */
            hostnames?: string[];
            /**
             * Kind
             * @default cloudflare
             * @constant
             */
            kind: "cloudflare";
            /**
             * Zone Id
             * @description Zone ID (32 hex characters, dashboard → Overview).
             */
            zone_id: string;
        };
        /**
         * ConfidenceLevel
         * @enum {string}
         */
        ConfidenceLevel: "low" | "medium" | "high";
        /** ConnectionTest */
        ConnectionTest: {
            /**
             * Auth Ok
             * @description Null when the source could not be reached.
             */
            auth_ok: boolean | null;
            /** Checked At */
            checked_at: string;
            /** Families */
            families?: components["schemas"]["FamilyCapability"][];
            /**
             * History Days
             * @description Days of matching history found, up to 30.
             */
            history_days?: number | null;
            /** @default prometheus */
            kind: components["schemas"]["SourceKind"];
            /**
             * Matched Series
             * @description Prometheus: series currently matching all matchers. Cloudflare: requests in the last 24 h. Sentry: error events and transactions in the last 24 h. Wazuh: alerts of the selected agents in the last 24 h.
             */
            matched_series?: number | null;
            /** Message */
            message?: string | null;
            /** Reachable */
            reachable: boolean;
        };
        /**
         * ConnectionTestRequest
         * @description Body of POST /api/projects/test-connection: a draft, possibly reusing stored secrets.
         */
        ConnectionTestRequest: {
            /**
             * Matchers
             * @description Required with a Prometheus source.
             */
            matchers?: components["schemas"]["LabelMatcher"][];
            /**
             * Project Id
             * @description Reuse this project's stored secrets for omitted ones.
             */
            project_id?: string | null;
            /** Source */
            source: components["schemas"]["PrometheusSourceInput"] | components["schemas"]["CloudflareSourceInput"] | components["schemas"]["SentrySourceInput"] | components["schemas"]["WazuhSourceInput"];
        };
        /**
         * DailyTrend
         * @description One 24-hour bucket; bucket_index 0 is the latest day [T-24h, T).
         */
        DailyTrend: {
            /**
             * Affected Entities
             * @description Entity keys.
             */
            affected_entities: string[];
            /** Anomalous Minutes */
            anomalous_minutes: number;
            /**
             * Anomalous Share
             * @description Null when nothing was observed.
             */
            anomalous_share: number | null;
            /** Baseline Days Used */
            baseline_days_used: number;
            /** Bucket Index */
            bucket_index: number;
            /** Coverage */
            coverage: number;
            /** Episode Count */
            episode_count: number;
            /** Episodes */
            episodes: components["schemas"]["EpisodeSummary"][];
            /**
             * Observed Entity Minutes
             * @description Eligible denominator.
             */
            observed_entity_minutes: number;
            peak_severity: components["schemas"]["Severity"] | null;
            status: components["schemas"]["TrendBucketStatus"];
            window: components["schemas"]["TimeRange"];
        };
        /**
         * DetectionMethod
         * @enum {string}
         */
        DetectionMethod: "relative" | "absolute";
        /**
         * Entity
         * @description Resource identity built from actual labels only; never inferred across namespaces.
         */
        Entity: {
            /** Display Name */
            display_name: string;
            /**
             * Key
             * @description Stable canonical key, e.g. 'node|job=node|instance=shop-production'.
             */
            key: string;
            kind: components["schemas"]["EntityKind"];
            /**
             * Labels
             * @description Identity labels only (no scope matchers).
             */
            labels: {
                [key: string]: string;
            };
        };
        /**
         * EntityKind
         * @enum {string}
         */
        EntityKind: "node" | "filesystem" | "disk" | "network_interface" | "container" | "service" | "route" | "proxy" | "upstream" | "database" | "zone" | "application" | "agent";
        /** EpisodeSummary */
        EpisodeSummary: {
            /** End */
            end: string;
            entity: components["schemas"]["Entity"];
            /** Episode Id */
            episode_id: string;
            /** Expected Median */
            expected_median: number | null;
            family: components["schemas"]["SignalFamily"];
            /**
             * Finding Id
             * @description Set only for latest-day episodes with evidence.
             */
            finding_id: string | null;
            /** Peak Observed */
            peak_observed: number;
            severity: components["schemas"]["Severity"];
            /** Signal */
            signal: string;
            /** Start */
            start: string;
            unit: components["schemas"]["Unit"];
        };
        /**
         * ErrorCode
         * @enum {string}
         */
        ErrorCode: "validation_error" | "project_not_found" | "project_name_taken" | "project_busy" | "source_not_configured" | "credentials_unreadable" | "analysis_not_found" | "report_not_ready" | "report_unavailable" | "schema_unsupported" | "analysis_not_active" | "queue_full" | "metrics_source_unavailable" | "end_time_invalid" | "interrupted_by_restart" | "job_timeout" | "internal_error" | "not_implemented";
        /**
         * Evidence
         * @description Chart data for a finding, persisted so a report reopens without the source.
         */
        Evidence: {
            /** Evidence Id */
            evidence_id: string;
            /** Expected */
            expected?: (number | null)[] | null;
            /** Finding Id */
            finding_id: string;
            /** Lower */
            lower?: (number | null)[] | null;
            series: components["schemas"]["MetricSeries"];
            /** Threshold */
            threshold?: number | null;
            /** Threshold Label */
            threshold_label?: string | null;
            /** Upper */
            upper?: (number | null)[] | null;
        };
        /**
         * Exclusion
         * @description Something omitted from the report, always disclosed (codes in docs/contracts.md).
         */
        Exclusion: {
            /** Code */
            code: string;
            family?: components["schemas"]["SignalFamily"] | null;
            /** Finding Id */
            finding_id?: string | null;
            /** Message */
            message: string;
        };
        /** ExpectedValue */
        ExpectedValue: {
            /** Lower */
            lower: number;
            /** Median */
            median: number;
            unit: components["schemas"]["Unit"];
            /** Upper */
            upper: number;
        };
        /** Explanation */
        Explanation: {
            /** Generated At */
            generated_at: string;
            /** Hypotheses */
            hypotheses: components["schemas"]["Hypothesis"][];
            /** Investigation Steps */
            investigation_steps: components["schemas"]["InvestigationStep"][];
            /** Model */
            model: string;
            /** Provider */
            provider: string;
            /** Summary */
            summary: string;
            /** Uncertainty */
            uncertainty: string;
        };
        /** ExplanationResult */
        ExplanationResult: {
            explanation?: components["schemas"]["Explanation"] | null;
            /**
             * Reason
             * @description Why failed/not_configured/disabled.
             */
            reason?: string | null;
            status: components["schemas"]["ExplanationStatus"];
            /**
             * Validation Notes
             * @description E.g. dropped items referencing unknown finding IDs.
             */
            validation_notes?: string[];
        };
        /**
         * ExplanationStatus
         * @enum {string}
         */
        ExplanationStatus: "disabled" | "not_configured" | "pending" | "succeeded" | "failed" | "skipped_no_findings";
        /** FamilyCapability */
        FamilyCapability: {
            family: components["schemas"]["SignalFamily"];
            /** Reason */
            reason?: string | null;
            status: components["schemas"]["CapabilityStatus"];
        };
        /** Finding */
        Finding: {
            /**
             * Attributes
             * @description Descriptive labels, e.g. error_type; not identity.
             */
            attributes?: {
                [key: string]: string;
            };
            /** Baseline Days */
            baseline_days: number | null;
            baseline_mode: components["schemas"]["BaselineMode"] | null;
            confidence: components["schemas"]["ConfidenceLevel"];
            /**
             * Confidence Reasons
             * @description Every factor that lowered confidence; empty when high.
             */
            confidence_reasons: components["schemas"]["Reason"][];
            /** Detector */
            detector: string;
            /** Detector Version */
            detector_version: string;
            /** Duration Seconds */
            duration_seconds: number;
            /** End */
            end: string;
            entity: components["schemas"]["Entity"];
            /** Evidence Ids */
            evidence_ids: string[];
            /** @description Null for absolute-only findings. */
            expected: components["schemas"]["ExpectedValue"] | null;
            family: components["schemas"]["SignalFamily"];
            /** Finding Id */
            finding_id: string;
            method: components["schemas"]["DetectionMethod"];
            /** @description Peak observed value in the episode. */
            observed: components["schemas"]["ObservedValue"];
            /** Peak At */
            peak_at: string;
            /**
             * Peak Score
             * @description Robust z-score; null for absolute checks.
             */
            peak_score: number | null;
            /**
             * Prior Episode Days
             * @default 0
             */
            prior_episode_days: number;
            /** @default new */
            recurrence: components["schemas"]["Recurrence"];
            /**
             * Related Finding Ids
             * @description Findings sharing identity labels only.
             */
            related_finding_ids?: string[];
            severity: components["schemas"]["Severity"];
            /** Severity Points */
            severity_points: number;
            /** Signal */
            signal: string;
            /** Start */
            start: string;
            /** @default resolved */
            state: components["schemas"]["FindingState"];
            /**
             * Threshold
             * @description Heuristic threshold for absolute checks.
             */
            threshold: number | null;
            /** Title */
            title: string;
        };
        /**
         * FindingState
         * @enum {string}
         */
        FindingState: "ongoing" | "resolved";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Database
             * @description 'ok' or 'unavailable'.
             */
            database: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * Hypothesis
         * @description Always presented as unverified.
         */
        Hypothesis: {
            /** Finding Ids */
            finding_ids: string[];
            likelihood: components["schemas"]["Likelihood"];
            /** Text */
            text: string;
        };
        /** InvestigationStep */
        InvestigationStep: {
            /** Finding Ids */
            finding_ids?: string[];
            /** Text */
            text: string;
        };
        /** JobError */
        JobError: {
            code: components["schemas"]["ErrorCode"];
            /** Message */
            message: string;
        };
        /**
         * JobState
         * @enum {string}
         */
        JobState: "queued" | "running" | "completed" | "partial" | "failed" | "cancelled";
        /**
         * JobTrigger
         * @enum {string}
         */
        JobTrigger: "manual" | "scheduled";
        /**
         * LabelMatcher
         * @description Exact ``name="value"`` matcher added to every selector of a project's queries.
         */
        LabelMatcher: {
            /** Name */
            name: string;
            /** Value */
            value: string;
        };
        /**
         * Likelihood
         * @enum {string}
         */
        Likelihood: "plausible" | "possible" | "speculative";
        /** Limits */
        Limits: {
            /** Max Queued Jobs */
            max_queued_jobs: number;
            /** Max Running Jobs */
            max_running_jobs: number;
            /** Max Series Per Job */
            max_series_per_job: number;
            /** Max Series Per Query */
            max_series_per_query: number;
            /** Query Timeout Seconds */
            query_timeout_seconds: number;
            /** Report Max Bytes */
            report_max_bytes: number;
        };
        /**
         * MetricCapability
         * @description Whether a signal family can be analysed for a scope, and why (not).
         */
        MetricCapability: {
            family: components["schemas"]["SignalFamily"];
            /**
             * History Days
             * @description Observed history for the scope; not proof of retention.
             */
            history_days?: number | null;
            /** Observed Metrics */
            observed_metrics?: string[];
            /** Reason */
            reason?: string | null;
            /** Required Labels */
            required_labels: string[];
            /** Required Metrics */
            required_metrics: string[];
            /** Signal */
            signal: string;
            /** @default prometheus */
            source: components["schemas"]["SourceKind"];
            status: components["schemas"]["CapabilityStatus"];
            /**
             * Verified
             * @description True only when observed in the live source.
             */
            verified: boolean;
        };
        /**
         * MetricSeries
         * @description One scoped series on a regular grid: values[i] is at start + i * step_seconds.
         *
         *     `None` is a gap (no sample), never zero.
         */
        MetricSeries: {
            /**
             * Coverage
             * @description Share of steps with a sample.
             */
            coverage: number;
            entity: components["schemas"]["Entity"];
            family: components["schemas"]["SignalFamily"];
            /**
             * Labels
             * @description All retained labels of the result series.
             */
            labels: {
                [key: string]: string;
            };
            /**
             * Query
             * @description Exact query sent to the source (PromQL/MetricsQL, GraphQL).
             */
            query: string;
            /**
             * Sample Interval
             * @description Mean sampling interval of the source data (1 = every event counted; Cloudflare adaptive sampling). Null when the source does not sample.
             */
            sample_interval?: number | null;
            /** Series Id */
            series_id: string;
            /**
             * Signal
             * @description Derived signal, e.g. 'cpu_utilization'.
             */
            signal: string;
            /** Start */
            start: string;
            /** Step Seconds */
            step_seconds: number;
            unit: components["schemas"]["Unit"];
            /** Values */
            values: (number | null)[];
        };
        /** NoAuth */
        NoAuth: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "none";
        };
        /** ObservedValue */
        ObservedValue: {
            unit: components["schemas"]["Unit"];
            /** Value */
            value: number;
        };
        /**
         * Problem
         * @description RFC 9457 problem details (application/problem+json).
         */
        Problem: {
            code: components["schemas"]["ErrorCode"];
            /** Detail */
            detail?: string | null;
            /** Errors */
            errors?: {
                [key: string]: string;
            }[] | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /**
             * Type
             * @default about:blank
             */
            type: string;
        };
        /** Project */
        Project: {
            /** Created At */
            created_at: string;
            /**
             * Credentials Readable
             * @description False when stored secrets cannot be decrypted (lost or changed key).
             * @default true
             */
            credentials_readable: boolean;
            /** Description */
            description?: string | null;
            /**
             * Keep Reports
             * @description Newest reports kept; null keeps all.
             */
            keep_reports?: number | null;
            /** Matchers */
            matchers: components["schemas"]["LabelMatcher"][];
            /** Name */
            name: string;
            /**
             * Next Scheduled Run
             * @description Next automatic analysis; null without a schedule.
             */
            next_scheduled_run?: string | null;
            /** Project Id */
            project_id: string;
            schedule?: components["schemas"]["ReportSchedule"] | null;
            /** Sources */
            sources: (components["schemas"]["PrometheusSource"] | components["schemas"]["CloudflareSource"] | components["schemas"]["SentrySource"] | components["schemas"]["WazuhSource"])[];
            /** Updated At */
            updated_at: string;
        };
        /**
         * ProjectInput
         * @description Body of POST /api/projects and PUT /api/projects/{project_id}.
         */
        ProjectInput: {
            /** Description */
            description?: string | null;
            /**
             * Keep Reports
             * @description Keep only this many newest reports; older analyses are deleted automatically. Null keeps all.
             */
            keep_reports?: number | null;
            /**
             * Matchers
             * @description Required (1-10) with a Prometheus source.
             */
            matchers?: components["schemas"]["LabelMatcher"][];
            /** Name */
            name: string;
            /** @description Automatic analyses; null runs analyses on demand only. */
            schedule?: components["schemas"]["ReportSchedule"] | null;
            /** Sources */
            sources?: (components["schemas"]["PrometheusSourceInput"] | components["schemas"]["CloudflareSourceInput"] | components["schemas"]["SentrySourceInput"] | components["schemas"]["WazuhSourceInput"])[];
        };
        /** ProjectList */
        ProjectList: {
            /** Items */
            items: components["schemas"]["ProjectSummary"][];
        };
        /**
         * ProjectSummary
         * @description A project with its analysis activity (list and detail pages).
         */
        ProjectSummary: {
            /** @description Queued or running job. */
            active_analysis?: components["schemas"]["AnalysisJob"] | null;
            /** Created At */
            created_at: string;
            /**
             * Credentials Readable
             * @description False when stored secrets cannot be decrypted (lost or changed key).
             * @default true
             */
            credentials_readable: boolean;
            /** Description */
            description?: string | null;
            /**
             * Keep Reports
             * @description Newest reports kept; null keeps all.
             */
            keep_reports?: number | null;
            /** @description Newest finished job. */
            latest_analysis?: components["schemas"]["AnalysisJob"] | null;
            /** Matchers */
            matchers: components["schemas"]["LabelMatcher"][];
            /** Name */
            name: string;
            /**
             * Next Scheduled Run
             * @description Next automatic analysis; null without a schedule.
             */
            next_scheduled_run?: string | null;
            /** Project Id */
            project_id: string;
            /**
             * Report Count
             * @description Saved reports (deleted with it).
             * @default 0
             */
            report_count: number;
            schedule?: components["schemas"]["ReportSchedule"] | null;
            /** Sources */
            sources: (components["schemas"]["PrometheusSource"] | components["schemas"]["CloudflareSource"] | components["schemas"]["SentrySource"] | components["schemas"]["WazuhSource"])[];
            /** Updated At */
            updated_at: string;
        };
        /** PrometheusSource */
        PrometheusSource: {
            /** Auth */
            auth: components["schemas"]["NoAuth"] | components["schemas"]["BearerAuth"] | components["schemas"]["BasicAuth"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "prometheus";
            /** Tls Verify */
            tls_verify: boolean;
            /** Url */
            url: string;
        };
        /** PrometheusSourceInput */
        PrometheusSourceInput: {
            /** Auth */
            auth?: components["schemas"]["NoAuth"] | components["schemas"]["BearerAuthInput"] | components["schemas"]["BasicAuthInput"];
            /**
             * Kind
             * @default prometheus
             * @constant
             */
            kind: "prometheus";
            /**
             * Tls Verify
             * @default true
             */
            tls_verify: boolean;
            /** Url */
            url: string;
        };
        /**
         * Reason
         * @description Machine code plus human message, used for confidence, coverage, and exclusions.
         */
        Reason: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /**
         * Recurrence
         * @enum {string}
         */
        Recurrence: "new" | "repeated" | "recurring";
        /**
         * ReportSchedule
         * @description Run an analysis automatically at ``time`` (local to ``timezone``) on ``weekdays``.
         *
         *     Each run analyses the 24 h ending at the scheduled instant.
         */
        ReportSchedule: {
            /**
             * Time
             * @description Local time of day, HH:MM (24 h).
             * @example 08:00
             */
            time: string;
            /**
             * Timezone
             * @description IANA time zone, e.g. Europe/Berlin.
             * @default UTC
             */
            timezone: string;
            /**
             * Weekdays
             * @description Days to run on; all days by default.
             */
            weekdays?: components["schemas"]["Weekday"][];
        };
        /**
         * ReportState
         * @enum {string}
         */
        ReportState: "completed" | "partial";
        /**
         * RuntimeConfig
         * @description GET /api/config — public runtime facts, never secrets.
         */
        RuntimeConfig: {
            /** Ai Model */
            ai_model: string | null;
            /** Ai Provider */
            ai_provider: string;
            /** Config Hash */
            config_hash: string;
            /** Database Bytes */
            database_bytes?: number | null;
            /** Detector Version */
            detector_version: string;
            /** @description disabled, not_configured, or pending (configured, per-report status varies). */
            explanation_status: components["schemas"]["ExplanationStatus"];
            limits: components["schemas"]["Limits"];
            /** Report Count */
            report_count?: number | null;
            /** Version */
            version: string;
        };
        /**
         * Scope
         * @description One project: every Prometheus query carries all of its matchers; reports stay inside it.
         *
         *     ``matchers`` is empty only for projects without a Prometheus source; Prometheus queries
         *     refuse an empty scope.
         */
        Scope: {
            /** Matchers */
            matchers: components["schemas"]["LabelMatcher"][];
            /** Project Id */
            project_id: string;
            /** Project Name */
            project_name: string;
        };
        /** SentrySource */
        SentrySource: {
            /** Api Url */
            api_url: string;
            /** Environment */
            environment?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "sentry";
            /** Organization */
            organization: string;
            /** Projects */
            projects: string[];
            /** Tags */
            tags?: components["schemas"]["SentryTag"][];
            /**
             * Tls Verify
             * @default true
             */
            tls_verify: boolean;
            /** Token Set */
            token_set: boolean;
        };
        /**
         * SentrySourceInput
         * @description Sentry projects of one organization, optionally narrowed to an environment and tags.
         */
        SentrySourceInput: {
            /**
             * Api Url
             * @description Sentry base URL: https://sentry.io, https://de.sentry.io for EU organizations, or a self-hosted instance (path prefixes are kept); synthetic://<scenario> for demo data.
             * @default https://sentry.io
             */
            api_url: string;
            /**
             * Auth Token
             * @description Auth token with org:read and project:read. Omit to keep the stored one (update only); not needed for synthetic://.
             */
            auth_token?: string | null;
            /**
             * Environment
             * @description Analyse only this environment; null analyses all of them.
             */
            environment?: string | null;
            /**
             * Kind
             * @default sentry
             * @constant
             */
            kind: "sentry";
            /**
             * Organization
             * @description Organization slug (Settings → General).
             */
            organization: string;
            /**
             * Projects
             * @description Project slugs (Settings → Projects); each is analysed as its own entity.
             */
            projects: string[];
            /**
             * Tags
             * @description Tag filters applied to every project, all of which must match.
             */
            tags?: components["schemas"]["SentryTag"][];
            /**
             * Tls Verify
             * @description Verify the server's TLS certificate; turn off only for a self-hosted Sentry with a self-signed or internal certificate.
             * @default true
             */
            tls_verify: boolean;
        };
        /**
         * SentryTag
         * @description Exact ``key:"value"`` tag filter added to every Sentry query of the source.
         */
        SentryTag: {
            /**
             * Key
             * @description Tag key, e.g. server_name, release or a custom tag.
             */
            key: string;
            /** Value */
            value: string;
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "low" | "medium" | "high" | "critical";
        /**
         * SignalCoverage
         * @description One row of the report coverage table.
         */
        SignalCoverage: {
            /** Baseline Days */
            baseline_days?: number | null;
            capability: components["schemas"]["CapabilityStatus"];
            /** Evaluated Series */
            evaluated_series: number;
            family: components["schemas"]["SignalFamily"];
            /** Reasons */
            reasons?: components["schemas"]["Reason"][];
            status: components["schemas"]["SignalStatus"];
            /** Total Series */
            total_series: number;
        };
        /**
         * SignalFamily
         * @enum {string}
         */
        SignalFamily: "cpu" | "memory" | "filesystem" | "disk_io" | "network" | "container" | "request_traffic" | "request_failures" | "client_errors" | "latency" | "proxy" | "database" | "edge" | "security" | "app_errors" | "app_performance" | "host_security" | "file_integrity";
        /**
         * SignalStatus
         * @enum {string}
         */
        SignalStatus: "anomalous" | "no_anomaly" | "insufficient_data" | "unsupported" | "source_error" | "not_evaluated";
        /**
         * SourceInfo
         * @description Identity of a data source without credentials.
         */
        SourceInfo: {
            /**
             * Backend
             * @description E.g. 'victoriametrics' when detected.
             */
            backend?: string | null;
            /**
             * Base Url
             * @description Scheme, host, port, and path prefix; never userinfo.
             */
            base_url: string;
            /** @default prometheus */
            kind: components["schemas"]["SourceKind"];
            /** Version */
            version?: string | null;
        };
        /**
         * SourceKind
         * @enum {string}
         */
        SourceKind: "prometheus" | "cloudflare" | "sentry" | "wazuh";
        /**
         * StageName
         * @enum {string}
         */
        StageName: "discovery" | "collection" | "detection" | "trends" | "explanation" | "saving";
        /** StageProgress */
        StageProgress: {
            /** Done */
            done?: number | null;
            /** Finished At */
            finished_at?: string | null;
            /** Message */
            message?: string | null;
            stage: components["schemas"]["StageName"];
            /** Started At */
            started_at?: string | null;
            status: components["schemas"]["StageStatus"];
            /** Total */
            total?: number | null;
        };
        /**
         * StageStatus
         * @enum {string}
         */
        StageStatus: "pending" | "running" | "done" | "failed" | "skipped";
        /**
         * TimeRange
         * @description Half-open interval [start, end).
         */
        TimeRange: {
            /** End */
            end: string;
            /** Start */
            start: string;
        };
        /**
         * TrendBucketStatus
         * @enum {string}
         */
        TrendBucketStatus: "ok" | "insufficient_baseline" | "insufficient_data" | "source_error";
        /**
         * TrendDirection
         * @enum {string}
         */
        TrendDirection: "worsening" | "improving" | "stable" | "inconclusive";
        /**
         * TrendSummary
         * @description Direction of the 14-day trend: last 7 buckets vs the 7 before, by anomalous share.
         */
        TrendSummary: {
            confidence: components["schemas"]["ConfidenceLevel"];
            direction: components["schemas"]["TrendDirection"];
            /** Previous Episodes */
            previous_episodes: number;
            /** Previous Share */
            previous_share: number | null;
            /** Reason */
            reason: string;
            /** Recent Episodes */
            recent_episodes: number;
            /** Recent Share */
            recent_share: number | null;
        };
        /**
         * Unit
         * @enum {string}
         */
        Unit: "ratio" | "bytes" | "bytes_per_second" | "requests_per_second" | "per_second" | "seconds" | "count";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WazuhLabel
         * @description Exact ``agent.labels.<key> = value`` filter (an agent's ``<labels>`` setting).
         */
        WazuhLabel: {
            /**
             * Key
             * @description Label key as set in the agent's <labels> block, e.g. project.
             */
            key: string;
            /** Value */
            value: string;
        };
        /** WazuhSource */
        WazuhSource: {
            /** Agents */
            agents?: string[];
            /** Api Url */
            api_url: string;
            /** Groups */
            groups?: string[];
            /**
             * Index Pattern
             * @default wazuh-alerts-4.x-*
             */
            index_pattern: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "wazuh";
            /** Labels */
            labels?: components["schemas"]["WazuhLabel"][];
            /**
             * Monitoring Index Pattern
             * @default wazuh-monitoring-*
             */
            monitoring_index_pattern: string;
            /** Password Set */
            password_set: boolean;
            /**
             * Tls Verify
             * @default true
             */
            tls_verify: boolean;
            /** Username */
            username?: string | null;
        };
        /**
         * WazuhSourceInput
         * @description Wazuh agents selected by name, group and/or agent labels, read from the Wazuh indexer.
         *
         *     The named agents and the groups' members together form the selection; label filters
         *     narrow it (or alone select every agent that has those labels).
         */
        WazuhSourceInput: {
            /**
             * Agents
             * @description Agent names (agent.name); each is analysed as its own entity.
             */
            agents?: string[];
            /**
             * Api Url
             * @description Wazuh indexer URL, e.g. https://wazuh-indexer:9200 (path prefixes are kept); synthetic://<scenario> for demo data.
             */
            api_url: string;
            /**
             * Groups
             * @description Agent groups; their current members (from the monitoring index) are analysed together with the named agents.
             */
            groups?: string[];
            /**
             * Index Pattern
             * @description Alerts index pattern of the indexer.
             * @default wazuh-alerts-4.x-*
             */
            index_pattern: string;
            /**
             * Kind
             * @default wazuh
             * @constant
             */
            kind: "wazuh";
            /**
             * Labels
             * @description Agent label filters (agent.labels.<key>), all of which must match.
             */
            labels?: components["schemas"]["WazuhLabel"][];
            /**
             * Monitoring Index Pattern
             * @description Index of the agent snapshots the Wazuh dashboard writes; used to resolve groups.
             * @default wazuh-monitoring-*
             */
            monitoring_index_pattern: string;
            /**
             * Password
             * @description Omit to keep the stored password (update only); not needed for synthetic://.
             */
            password?: string | null;
            /**
             * Tls Verify
             * @description Verify the indexer's TLS certificate; turn off only for a self-signed or internal certificate (the Wazuh default).
             * @default true
             */
            tls_verify: boolean;
            /**
             * Username
             * @description Indexer user with read access to the alerts indices; not needed for synthetic://.
             */
            username?: string | null;
        };
        /**
         * Weekday
         * @enum {string}
         */
        Weekday: "mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_analyses_api_analyses_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisList"];
                };
            };
            /** @description Problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
        };
    };
    submit_analysis_api_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisSubmission"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisSubmitted"];
                };
            };
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisSubmitted"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Problem */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Problem */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
        };
    };
    get_analysis_api_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisJob"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_analysis_api_analyses__analysis_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisJob"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Problem */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_analyses__analysis_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisReport"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Problem */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runtime_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeConfig"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectList"];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: {
                /** @description Clone: reuse this project's stored secrets for omitted ones. */
                clone_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Problem */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
        };
    };
    test_connection_api_projects_test_connection_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionTest"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Problem */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_projects__project_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Problem */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
        };
    };
    delete_project_api_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Problem */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_health_api_projects__project_id__health_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionTest"][];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Problem */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
